### ISSUE TITLE
Forms do not bubble-up model validation errors

### ISSUE THREAD

**Issue by bbuchalter** [DynamoMTL/spree_one_page_checkout#10]
Perhaps I'm doing something wrong here, but it seems I have to duplicate all my model validations in my OPCO forms. For example, in the `CreditCardForm`, if Spree's card expiration validation fails, I get a 422 back from the `render_event_response` controller action that looks like this:

```
Started POST "/spree/checkout/render_event_response?source=new_credit_card_entry&type=create_credit_card" for 127.0.0.1 at 2014-05-20 16:16:04 -0600
Processing by Spree::CheckoutController#render_event_response as JS
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"P3bD/XFQsivA9vkNxUggGg/cL2AWuOI4pnsl1USNoqU=", "credit_card"=>{"user_id"=>"10451", "number"=>"[FILTERED]", "month"=>"1", "year"=>"2014", "verification_value"=>"[FILTERED]"}, "commit"=>"Add Card", "source"=>"new_credit_card_entry", "type"=>"create_credit_card"}

Completed 422 Unprocessable Entity in 58.1ms

ActiveRecord::RecordInvalid (Validation failed: Card has expired):
```

Worse yet, the response back from the server is Rails's exception handler HTML, so I can't even handle 422s. Would love to hear if I'm missing something here!

Thanks!

**Comment by DanielWright** [comment]
I don't have an off-the-cuff answer for you here. Would you be able to submit a PR with a fix, or a failing  spec?
