### ISSUE TITLE
Handling gateway errors in the confirm step of checkout

### ISSUE THREAD

**Issue by bbuchalter** [DynamoMTL/spree_one_page_checkout#11]
Setup:
As a returning customer
Given I have credit card in my profile which is no longer valid
When I use this credit card to complete my order

Expected behavior:
Then I am told my card was declined

Actual behavior:
Then the checkout fails without error

This was discovered using [Stripe's test cards](https://stripe.com/docs/testing) which includes an option with this description: "Attaching this card to a Customer object will succeed, but attempts to charge the customer will fail." After talking with Stripe support, they explained this can happen with cards in profiles which are later reported lost or stolen.

Perhaps it's just my implementation, but it seems that in the confirm step does not attempt to handle gateway errors. Am I missing something?

**Comment by DanielWright** [comment]
You're correct, the extension does not natively handle gateway errors. It was one of the features I baked directly into TJ for expediency, which I had the intention of back-porting more cleanly into OPCO, but never found the opportunity/time for. I'd be thrilled to see a PR for this.
