### ISSUE TITLE
Memoized @_address_form undesirable?

### ISSUE THREAD

**Issue by bbuchalter** [DynamoMTL/spree_one_page_checkout#9]
As a user of one page checkout
When I create a new address and save it to my address book
And then go to add another address to my address book
Then I should not see the address that I just added pre-populating all the fields of my new address

Forgive me for not submitting a proper pull request, but it's not clear if this is desired or undesired behavior. I believe this is caused by the memoization of the address form on https://github.com/DynamoMTL/spree_one_page_checkout/blob/2-3-stable/app/widgets/one_page_checkout/address_book/new_address_widget.rb#L41

Thank you for making this a private method, and thus easily overridable, but I thought I'd share what I considered undesirable behavior.

**Comment by bbuchalter** [comment]
I believe I understand now why this was done; to allow the form to be re-rendered if validation fails. I worked around it with this implementation:

```
def address_form
  if @_address_form.blank? || @_address_form.persisted?
    @_address_form = address_form_factory.new(::Spree::Address.new)
  else
    @_address_form
  end
end
```

I'm not in love with it, but I thought I'd share. Please let me know if you'd rather I just close the issue. Thanks!

**Comment by bbuchalter** [comment]
Forgive me for learning out loud, but I no longer think the above code is what I want. I actually wanted something like this:

```
  def create_address(event)
    if address = create_address_service.call(event.data.fetch(:address))
      @_address_form = nil   # <== THIS IS NEW
      trigger :address_created, address: address
    else
      replace state: :form
    end
  end
```

**Comment by DanielWright** [comment]
@bbuchalter 

Good catch. I'm not crazy about your fix, because having to manipulate a memoization variable itself suggests a smell in my original memoizing code! I didn't realize that the address form would maintain state when the panel widget redraws itself after an `:address_created` event.

What do you think about something along the lines of:

```
def address_form
  address_form_factory.new(Spree::Address.new(address_params))
end

def address_params
  params.fetch(:address, {})
end
```

**Comment by bbuchalter** [comment]
@DanielWright forgive me for the long delay in responding. I agree completely that my proposed implementation was not ideal. Just wanted to communicate my intent while it was still fresh (and a mess) in my head. You're implementation passes my tests, so I think that would be an improvement. Forgive me for not keeping closer track of the code, but has this already made it in to the 2-3-stable branch? If so, I'll close the issue.

**Comment by bbuchalter** [comment]
@DanielWright well, it seems I spoke to soon. Other regression tests later identified that this solution would not work when selecting an existing address from the address book. To see why, take a look at the params getting passed along:

```
Started GET "/spree/checkout/render_event_response?address=50319&source=shipping_address_book_entry&type=assign_address" for 127.0.0.1 at 2014-05-28 01:46:31 -0600
Processing by Spree::CheckoutController#render_event_response as JS
  Parameters: {"address"=>"50319", "source"=>"shipping_address_book_entry", "type"=>"assign_address"}
```

I'm sure there are several solutions, but it's not clear from my vantage what's best for OPCO. I'll defer to you.
